Lab2/Home/urls.py
# from django.urls import path
# from views import index


# app_name = "BookStore"
# urlpatterns = [
#     path("", views.index, name="home-index"),
#     # path("books/create", views.create, name="home-create"),
#     # path("books/store", views.store, name="home-store"),
#     # path("books/<int:id>/edit", views.edit, name="home-edit"),
#     # path("books/<int:id>", views.show, name="home-show"),
#     # path("books/<int:id>/delete", views.destroy, name="home-destroy"),
#     # path("books/<int:id>/update", views.update, name="home-update"),
# ]
from django.urls import path
from .views import *

app_name = 'BookStore'

urlpatterns = [
    path('',  index, name="book-index"),
    path("books/create", create, name="book-create"),
    path("books/store", store, name="book-store"),
    path("books/<int:id>", show, name="book-show"),
    path("books/<int:id>/delete", destroy, name="book-delete"),
    path("books/<int:id>/update", update, name="book-update"),
    path("books/<int:id>/edit", edit, name="book-edit")

]

Lab2/Lab2/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
]

Lab2/Home/models.py
# Create your models here.
from django.db import models
from django.utils.text import slugify


class Book(models.Model):
    author_name = models.CharField(max_length=30)
    title = models.CharField(max_length=100, unique=True)
    description = models.TextField()
    type= models.CharField(max_length=100)
    rate = models.IntegerField()
    views = models.IntegerField()
    slug = models.SlugField(unique=True, max_length=255, blank=True)
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Book, self).save(*args, **kwargs)

Lab2/Home/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_protect
from Home.models import Book
from .form import BookForm


def index(request):
    books = Book.objects.all().values()
    return render(request, "home/index.html", {"books": books})


def show(request, id):
    book = Book.objects.get(pk=id)
    return render(request, "home/show.html", {"book": book})


def edit(request, id):

    book = Book.objects.get(pk=id)
    form = BookForm(instance=book)
    return render(request, "home/edit.html", {'form':form , 'book':book})


def create(request):

    form = BookForm()
    return render(request, "home/create.html" , {"form" : form})


def store(request):

    form = BookForm(request.POST)
    if form.is_valid:
       form.save()
    return redirect('BookStore:book-index')

@csrf_protect
def update(request, id):
    book = Book.objects.get(pk=id)
    form = BookForm(request.POST, instance=book)
    if form.is_valid():  # Call is_valid() as a function
        form.save()
        return redirect("BookStore:book-index")
    else:
        # Handle invalid form data
        # You can display the form errors or perform any necessary actions
        pass



def destroy(request, id):

    book = Book.objects.get(pk=id)
    book.delete()
    return redirect("BookStore:book-index")

Lab2/Home/templates/home/create.html
{% extends 'main/base_layout.html' %}
{% load static %}

{% block title %}Create New Book{% endblock %}

{% block main-content %}
<link href="{% static 'Home/assets/css/formStyle.css' %}" rel="stylesheet">

<form class="container form" id="form-edit" method="POST" action="{% url 'BookStore:book-store' %}">
  <div class="title">Add New Book</div>
  {% csrf_token %} {% for field in form %}
  <div class="input-group">
    {{ field.errors }} {{ field.label_tag }} {{ field }}
  </div>
  {% endfor %}
  <button type="submit" class="btn btn-primary">Save</button>
</form>

{% endblock %}

Lab2/Home/templates/home/edit.html
{% extends 'main/base_layout.html' %}
{% load static %}

{% block title %}Create New Book{% endblock %}

{% block main-content %}
<link href="{% static 'Home/assets/css/formStyle.css' %}" rel="stylesheet">

<form class="container form" id="form-edit" method="POST"  action="{% url 'BookStore:book-update' book.id  %}">
  <div class="title">Update a Book</div>
  {% csrf_token %} {{form.as_p}}
  <button type="submit" class="btn btn-primary">Update</button>
</form>

{% endblock %}

Lab2/Home/templates/home/index.html
{% extends 'main/base_layout.html' %}

{# override block title #}
{% block title %}
    Books List
{% endblock %}

{# override body #}
{% block main-content %}
<div class="container" style="height: 90vh;">
    <div class="d-flex text-center my-4 justify-content-end ">
        <a class="btn btn-success" href="{% url 'BookStore:book-create' %}">Add New Book</a>
    </div>

    <table class="container table table-condensed text-center">
    <thead>
        <tr>
            <th> ID </th>
            <th> Title </th>
            <th> Description </th>
            <th> Type </th>
            <th> Rate </th>
            <th> Views </th>
            <th> Actions </th>
        </tr>
    </thead>
    
    <tbody>
        {% for book in books %}
        <tr>
        <td> {{ book.id }} </td>
        <td> {{ book.title }} </td>
        <td>{{ book.description | truncatewords:2 | title }}</td>
        <td> {{ book.type }} </td>
        <td> {{ book.rate }} </td>
        <td> {{ book.views }} </td>
        
        <td> 
            <a class="btn btn-primary text-light" href="{% url 'BookStore:book-show' book.id %}"> View</a>
            <a class="btn btn-danger text-light" href="{% url 'BookStore:book-delete' book.id %}"> Delete</a> 
            <a class="btn btn-info text-light" href="{% url 'BookStore:book-edit' book.id %}"> Update</a>
        </td>
    </tr>

    {% empty %}
    <tr>
        <td colspan="5" class="text-center"> Sorry, This Book Not Found in The List</td>
    </tr>
    {% endfor %}
    </tbody>

    </table>
</div>
{% endblock %}

Lab2/Home/templates/home/show.html
{% extends 'main/base_layout.html' %}


{% block main-content %}
<div class="container-fluid d-flex flex-column justify-content-center" style="height: 80vh">
  <h2 class="text-center fw-light"> Welcome to Book Details </h2>
  <div class="d-flex justify-content-center mt-3 p-2 ">
    <div class="card col-4 d-flex flex-column align-items-center">
        <div class="card-body d-flex flex-column align-items-center">
          <h5 class="card-title">Book Title: <span class="text-secondary">{{ book.title }}</span></h5>
          <p class="card-title">Book ID:<span class="text-secondary">{{ book.id }}</span></p>
          <p class="card-title">Book Author:<span class="text-secondary">{{ book.author_name }}</span></p>
          <p class="card-title">Book Description: <span class="text-secondary">{{ book.description }}</span></p>
          <p class="card-title">Book Type:<span class="text-secondary"> {{ book.type }}</span></p>
          <p class="card-title">Book Rate: <span class="text-secondary"> {{ book.rate }}</span></p>
          <p class="card-title">Book Views: <span class="text-secondary"> {{ book.views }}</span></p>

        </div>
    </div>
  </div>
</div>
{% endblock %}