lab1/book_store/book_store/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('books.urls')),
]

lab1/book_store/books/urls.py
from django.urls import path
from .views import index,show,delete,update
app_name = 'books'
urlpatterns = [
    path('books', index,name="books-index"),
    path('books/<int:id>', show,name="books-show"),
    path('books/<int:id>/delete', delete,name="books-delete"),
    path('books/<int:id>/update', update,name="books-update"),
    path('', index,name="books-index"),
]

lab1/book_store/books/models.py
from django.db import models

# Create your models here.

lab1/book_store/books/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect


book_list = [{
        'index': 0,
        'id': 1,
        'name': 'Book-1',
        'author': "charles dickens",
        'description': "book 1 description",
        "price":100
    }, {
        'index': 1,
        'id': 2,
        'name': 'Book-2',
        'author': "charlotte bronte",
        'description': "book 2 description",
        "price":200
    },  {
        'index': 2,
        'id': 3,
        'name': 'Book-3',
        'author': "William Shakespeare",
        'description': "book 3 description",
        "price":300
    },]
# Create your views here.
def index(request):
    context = {'book_list': book_list}
    return render(request, 'index.html',context)

def show(request,**kwargs):
    book=_get_book(kwargs.get('id'))
    print(book)
    context = {'book': book}
    return render(request, 'show.html',context)

def delete(request,**kwargs):
    book=_get_book(kwargs.get('id'))
    if book:
        book_list.remove( book)
    return redirect("books:books-index")

def update(request,**kwargs):
    book=_get_book(kwargs.get('id'))
    if book:
        # book_list.remove( book)
        book['description']=f"description updated"
    return redirect("books:books-index")

def _get_book(id):
    for book in book_list:
        if book['id']==id:
            return book
    return None

lab1/book_store/books/templates/index.html
{% extends 'main/layout.html' %}


{% block title %}
    book list
{% endblock %}

{% block main-content%}


<h1> Welcome to bookstore </h1>

<h3>book list</h3>

<table class="table">
    <thead>
        <tr>
            <td> ID </td>
            <td> Name </td>
            <td> Author </td>
            <td> Price </td>
            <td> Description </td>
            <td> Actions </td>


        </tr>   
    </thead>
    <tbody>
        {% for book in book_list %}
        <tr {% if book.price > 200 %} style="color:red" {% else %} style="color:green" {% endif %} >
            <td>{{ book.id }} </td>
            <td>{{ book.name }} </td>
            <td> {{ book.author }}</td>
            <td> {{ book.price }} </td>
            <td> {{ book.description | truncatewords:3 | title }} </td>
            <td> 
                <a class="btn btn-info" href="{% url 'books:books-show' book.id %}">show</a>
                <a class="btn btn-info" href="{% url 'books:books-update' book.id %}">update</a>
                <a class="btn btn-danger" href="{% url 'books:books-delete' book.id %}">delete</a>

            </td>


        </tr>
        {% endfor %}

    </tbody>

</table>

{% endblock %}

lab1/book_store/books/templates/show.html
{% extends 'main/layout.html' %}


{% block title %}
    book list
{% endblock %}


{% block main-content %}
    <h1> Welcome to book details </h1>
    <table class="table">
    <thead>
        <tr>
            <td> ID </td>
            <td> Name </td>
            <td> Author </td>
            <td> Price </td>
            <td> Description </td>
        </tr>
    </thead>
    <tbody>
        <tr {% if task_priority > 3 %} style="color:red" {% else %} style="color:green" {% endif %} >
            <td>{{ book.id }} </td>
            <td>{{ book.name }} </td>
            <td> {{ book.author }}</td>
            <td> {{ book.price }} </td>
            <td> {{ book.description | truncatewords:3 | title }} </td>
        </tr>
    </tbody>

    </table>


{% endblock %}